import { createTool } from '@mastra/core/tools';
import { getCoreServices } from '../../services/core.service';
import { z } from 'zod';

/**
 * Tool for creating new Vargos functions
 *
 * This tool generates function files, metadata, and auto-indexes for semantic search
 */
export const createFunctionTool = createTool({
  id: 'create-function' as const,
  description: 'Create a new Vargos function with metadata, code, and tests',
  inputSchema: z.object({
    name: z.string().describe('Function name (kebab-case)'),
    description: z.string().describe('Detailed description of what the function does'),
    version: z.string().describe('Function version in semver format (default: "1.0.0")'),
    category: z.union([z.string(), z.array(z.string())]).describe('Category or categories'),
    tags: z.array(z.string()).describe('Tags for categorization and search'),
    requiredEnvVars: z.array(z.string()).describe('Required environment variables, empty array if none'),
    input: z.array(z.object({
      name: z.string(),
      type: z.string(),
      description: z.string(),
      defaultValue: z.string().describe('Default value as string, empty string if none'),
    })).describe('Input parameters schema'),
    output: z.array(z.object({
      name: z.string(),
      type: z.string(),
      description: z.string().describe('Description, empty string if none'),
    })).describe('Output schema'),
    code: z.string().describe('TypeScript function code implementation'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    functionId: z.string(),
    message: z.string(),
  }),
  execute: async ({ context }): Promise<{
    success: boolean;
    functionId: string;
    message: string;
  }> => {
    const { name, description, version, category, tags, requiredEnvVars, input, output, code } = context;

    try {
      const coreServices = getCoreServices();

      // Create function metadata (id will be generated by provider)
      const functionMeta = await coreServices.functionsService.createFunction({
        metadata: {
          name,
          description,
          version,
          category,
          tags,
          requiredEnvVars,
          input: input as any,
          output: output as any,
        },
        code,
      });

      return {
        success: true,
        functionId: functionMeta.id,
        message: `Function '${name}' created successfully with ID: ${functionMeta.id}`,
      };
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      throw new Error(`Failed to create function: ${errorMessage}`);
    }
  },
});
