export const TOKENS = {
  LLM_PROVIDER: Symbol('LLM_PROVIDER'),
  VECTOR_PROVIDER: Symbol('VECTOR_PROVIDER'),
  FUNCTIONS_PROVIDER: Symbol('FUNCTIONS_PROVIDER'),
  ENV_PROVIDER: Symbol('ENV_PROVIDER'),
  LLM_SERVICE: Symbol('LLM_SERVICE'),
  VECTOR_SERVICE: Symbol('VECTOR_SERVICE'),
  FUNCTIONS_SERVICE: Symbol('FUNCTIONS_SERVICE'),
  ENV_SERVICE: Symbol('ENV_SERVICE'),
  SHELL_SERVICE: Symbol('SHELL_SERVICE'),
} as const;

